# Generated by Django 4.1.2 on 2022-10-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Оберіть автора книги', to='catalog.author', verbose_name='Автор книги'),
        ),
    ]
